#!/bin/bash

rsync -qr \
	--filter=':- /var/repos/${1}/.gitignore' \
	--delete \
 	/var/repos/${1}/ ${1}:${2}

if [  $? -eq 0 ]; then
	notify "Deploy complete for ${1}:${2} by ${LOGNAME}@${HOSTNAME}"
else
	notify-critical "rsync exited with code $? for ${LOGNAME}@${HOSTNAME} \
		while attempting to deploy ${1}"
fi

exit 0
