#!/bin/bash

rsync -a --delete /var/repos/${1}/ ${1}://var/www/html \
	&& notify "Deploy complete for ${1} by $USER@$HOSTNAME" \
	|| notify-critical "rsync exited withcode $? for $USER@$HOSTNAME \
		while attmpting to deploy ${1}"
