#!/bin/bash

DOMAIN="$1"
DISK="${2:-/dev/sda}"
LIMIT=80
if [[ "$DOMAIN" == "localhost" ]]; then
    ls -l "$DISK" || { notify "$DISK not found on $DOMAIN" critical; exit 1; }
    USED=$(df $DISK | awk '{print $5}' | sed -ne 2p | cut -d'%' -f1)
else
    ssh "$DOMAIN" "ls -l $DISK" || { notify "$DISK not found on $DOMAIN" critical; exit 1; }
    USED=$(ssh "$DOMAIN" "df $DISK | awk '{print \$5}' | sed -ne 2p | cut -d'%' -f1")
fi

if [ $USED -gt $LIMIT ]; then
    notify "$DISK space usage is at ${USED}% on $DOMAIN" critical
fi

exit 0
