#!/bin/bash

if [ $# -eq 0 ]; then
    echo "

Usage: do-new-wp CONFIGFILE

Config file vars, required:
NAME (alphanumeric and dashes only) 
FQDN (fully qualified domain name)
DOTOKEN
PUBLICKEY

ADMINIP is automatically pulled from eth0

Optional vars and their default values:
SIZE s-1vcpu-1gb
IMAGE lemp-16-04
REGION sfo2
"
    exit 1
fi
# Include the config file
. $1

ADMINIP="$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)"
SCRIPTDIR=$(dirname ${0})

# Set default values
SSHOSTS=${SSHOSTS:-~/.ssh/config}
SIZE=${SIZE:-s-1vcpu-1gb}
IMAGE=${IMAGE:-lemp-16-04}
REGION=${REGION:-sfo2}
# add ses creds
# generate db/wp passwords
MYSQLROOTPASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 18 | head -n 1)

# Check if the name is already taken
if grep -w ${NAME} ${SSHOSTS}; then
    echo "${NAME} found in current ssh config, exiting"
    exit 1
fi

# Provision the droplet
DID=$(doctl compute droplet create \
    ${NAME} \
    -t ${DOTOKEN} \
    -o json \
    --size ${SIZE} \
    --image ${IMAGE} \
    --region ${REGION} \
    --enable-backups \
    --enable-monitoring \
    | jq '.[0] .id' | tr -d '\n')

echo "Wait two secs for the droplet to be created..."
sleep 2

# Get IP from DO
DIP=$(doctl compute droplet get ${DID} -t ${DOTOKEN} -o json \
    | jq '.[0] .networks.v4[0].ip_address' | tr -d '\n')

# Setup ssh config file
echo "Host ${NAME}
    HostName ${DIP}
    User root
    IdentityFile=~/.ssh/id_rsa
    IdentitiesOnly yes
" >> ${SSHOSTS}

grep ${NAME} -A5 ${SSHOSTS}

# Setup ansible hosts file
cd ${SCRIPTDIR}/ansible

# Run ansible playbook to set up servers
ansible-playbook wordpress.yml --extra-vars "
    host=${NAME} 
    fqdn=${FQDN}
    mysql_root_password=${MYSQLROOTPASSWORD}"

# Run wordpress-install new / clone repo

# Uploads dir??

# Offer to delete the droplet
doctl compute droplet delete $DID

#doctl compute droplet list \
#    -o json \
#    | jq '.[] | select(.name=="${NAME}") | .id' 

exit 0
