#!/bin/bash

if [ $# -eq 0 ]; then
    echo "

Usage: do-new-wp CONFIGFILE
Provisions a new droplet at Digitalocean and installs WordPress.

Config file vars required, (see do-new-wp.conf.example):
    NAME (alphanumeric and dashes only) 
    FQDN (fully qualified domain name)
    EMAIL
    DOTOKEN
    PUBLICKEY

ADMINIP is automatically obtained from eth0

Optional vars and their default values:
    SSHHOSTS ~/.ssh/config
    ANSHOSTS /etc/ansible/hosts
    PATHTOPRIVKEY ~/.ssh/id_rsa
    SIZE s-1vcpu-1gb
    IMAGE ubuntu-16-04-x64
    REGION sfo2
    WPUSER admin
"
    exit 1
fi
# Include the config file
. $1

ADMINIP="$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)"
SCRIPTDIR=$(dirname ${0})

# Set default values
SSHHOSTS=${SSHHOSTS:-~/.ssh/config}
ANSHOSTS=${ANSHOSTS:-/etc/ansible/hosts}
PATHTOPRIVKEY=${PATHTOPRIVKEY:-~/.ssh/id_rsa}
SIZE=${SIZE:-s-1vcpu-1gb}
IMAGE=${IMAGE:-ubuntu-16-04-x64}
REGION=${REGION:-sfo2}
WPUSER=${WPUSER:-admin}
# add ses creds
# generate db/wp passwords
MYSQLROOTPASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 18 | head -n 1)
MYSQLWPPASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 18 | head -n 1)

# Check if the name is already taken
if grep -w ${NAME} ${SSHHOSTS}; then
    echo "${NAME} was found in the current ${SSHHOSTS}, exiting."
    exit 1
elif grep -w ${NAME} ${ANSHOSTS}; then
    echo "${NAME} was found in the current ${ANSHOSTS}, exiting."
    exit 1 
fi

# Provision the droplet
echo "Provisioning new droplet for ${NAME}"
DID=$(doctl compute droplet create \
    ${NAME} \
    -o json \
    -t ${DOTOKEN} \
    --ssh-keys ${PUBLICKEY} \
    --size ${SIZE} \
    --image ${IMAGE} \
    --region ${REGION} \
    --enable-backups \
    --enable-monitoring \
    | jq '.[0] .id' | tr -d '\n')

if [ ! $? -eq 0 ]; then
    echo "Error provisioning droplet."
    exit 1
else
    echo "Wait five seconds for the droplet to be created..."
    sleep 5
fi

# Get IP from DO
# and remove dbl quotes from string
echo "Getting IP from droplet ${DID}."
DIP=$(doctl compute droplet \
    get ${DID} \
    -t ${DOTOKEN} \
    -o json \
    | jq '.[0] .networks.v4[0].ip_address' | tr -d '\n')
DIP=$(echo "$DIP" | tr -d '"')

# Setup ssh config file for Ansible
# Later we must modify this for a non-root user
# and non-standard port
echo "Adding ${NAME} to ssh config file:"
echo "Host ${NAME}
    HostName ${DIP}
    User root
    IdentityFile ${PATHTOPRIVKEY}
    IdentitiesOnly yes
" >> ${SSHHOSTS}
# Echo the entry you just wrote
grep -w ${NAME} -A5 ${SSHHOSTS}

# Setup ansible hosts file
echo "${NAME} ansible_port=22 ansible_host=${DIP}" >> ${ANSHOSTS}
if [ ! $? -eq 0 ]; then
    echo "Error writing to ${ANSHOSTS}"
    exit 1
fi

echo -ne "Wait for the droplet initialisation to complete..."
sleep 10
while true; do
    ssh -o ConnectTimeout=3 -q ${NAME} "[ -f /var/lib/cloud/instance/boot-finished ]"
    if [ $? -eq 0 ]; then
        sleep 1
        break
    else
        echo -ne "."
        sleep 1
    fi
done

echo "Install prerequisite packages."
while true; do
    ssh -o ConnectTimeout=3 ${NAME} "apt-get -y -q install python ssl-cert"
    if [ $? -eq 0 ]; then
        sleep 3
        break
    else
        echo "Error installing packages, trying again..."
    fi
done

# Run ansible playbook to set up servers
cd ${SCRIPTDIR}/ansible
ansible-playbook wordpress.yml --extra-vars "
        mysql_root_password=${MYSQLROOTPASSWORD}
        mysql_wp_password=${MYSQLWPPASSWORD}
        fqdn=${FQDN}
        --limit ${NAME}"

# Run wordpress-install new / clone repo
cd ${SCRIPTDIR}
wordpress-install \
    ${NAME} \
    ${FQDN} \
    ${WPUSER} \
    ${EMAIL} \
    ${MYSQLWPPASSWORD}

# Change webroot permissions
ssh ${NAME} "chown -R www-data:www-data /var/www/html"

# Offer to delete the droplet
doctl compute droplet delete $DID

echo "
Root mysql password: ${MYSQLROOTPASSWORD}
Wordpress mysql password: ${MYSQLWPPASSWORD}
Test your new site at https://${DIP}
or https://${FQDN}
"

exit 0
