#!/bin/bash

USAGE="
Usage: do-wp-ansible CONFIGFILE
Provisions a new droplet at Digitalocean and installs WordPress.

Config file vars required, (see do-new-wp.conf.example):
    NAME (alphanumeric and dashes only) 
    DOMAIN
    SUBDOMAIN
    EMAIL

ADMINIP is automatically obtained from eth0

Optional vars and their default values:
    SSHHOSTS ~/.ssh/config
    ANSHOSTS /etc/ansible/hosts
"
# Print USAGE if no args
if [ $# -eq 0 ]; then
    echo "$USAGE"
    exit 1
fi

function main {
###
### VARIABLES ###
###
    local FQDN ADMINIP SCRIPTDIR 
    local SSHHOSTS ANSHOSTS 
# Include the config file
    . "$1"
# TODO add ses creds
# Check that required variables are set
    [ -z "$DOMAIN" ] && { echo "DOMAIN not set $DOMAIN"; exit 1; }
    [ -z "$SUBDOMAIN" ] && { echo "SUBDOMAIN not set $SUBDOMAIN"; exit 1; }
    [ -z "$EMAIL" ] && { echo "EMAIL not set $EMAIL"; exit 1; }
    [ -z "$DOTOKEN" ] && { echo "DOTOKEN not set $DOTOKEN"; exit 1; }
    [ -z "$PUBLICKEY" ] && { echo "PUBLICKEY not set $PUBLICKEY"; exit 1; }
    FQDN="${SUBDOMAIN}.${DOMAIN}"
    ADMINIP="$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)"
    SCRIPTDIR=$(dirname "${0}")
# Set default values for optional variables
    SSHHOSTS=${SSHHOSTS:-~/.ssh/config}
    ANSHOSTS=${ANSHOSTS:-/etc/ansible/hosts}

# Wait for the new droplet to become ready
    echo -ne "Wait for the droplet initialisation to complete..."
    while true; do
        ssh -o ConnectTimeout=3 -q "${NAME}" \
            "[ -f /var/lib/cloud/instance/boot-finished ]"
        if [ $? -eq 0 ]; then
            sleep 1
            echo -ne "\r"
            break
        else
            echo -ne "."
            sleep 1
        fi
    done

###
### INSTALL SOFTWARE ###
###
    echo "Install prerequisite packages."
    while true; do
        ssh -o ConnectTimeout=3 "${NAME}" \
            "DEBIAN_FRONTEND=noninteractive apt-get -y -q install python ssl-cert"
        if [ $? -eq 0 ]; then
            sleep 3
            break
        else
            echo "Error installing packages, trying again..."
        fi
    done
    ssh "$NAME" "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; chmod +x wp-cli.phar; mv wp-cli.phar /usr/local/bin/wp"
    if [ ! $? -eq 0 ]; then
        echo "Error installing wp-cli."
        exit 1
    fi
# Run ansible playbook to set up servers
    cd "${SCRIPTDIR}/ansible"
    ansible-playbook wordpress.yml --extra-vars "
        host=${NAME}
        adminip=${ADMINIP}
        mysql_root_password=${MYSQLROOTPASSWORD}
        mysql_wp_password=${MYSQLWPPASSWORD}
        fqdn=${FQDN}
        email=${EMAIL}"
    if [ ! $? -eq 0 ]; then
        echo "Error running ansible."
        exit 1
    fi
# Change webroot permissions
    wordpress-permissions "$NAME" dev || exit 1

    echo "
***

Ansible run completed for:
https://${FQDN}

***
    "
}

main "$@"
exit 0
