#!/bin/bash

deploypath=${2:-/var/www/html}
#	--delete \
rsync -qr \
	--filter=':- /var/repos/${1}/.gitignore' \
 	/var/repos/${1}/ ${1}:${deploypath}
if [ ! $? -eq 0 ]; then
	notify-critical "rsync exited with code $? for ${LOGNAME}@${HOSTNAME} \
		while attempting to deploy ${1}"
fi

if [  $? -eq 0 ]; then
	notify "Deploy complete for ${1}:${2} by ${LOGNAME}@${HOSTNAME}"
else
	notify-critical "wordpress-permissions exited with code $? for ${LOGNAME}@${HOSTNAME} \
		while attempting to deploy ${1}"
fi
wordpress-permissions "$1" dev

exit 0
