#!/bin/bash
USAGE="
$(basename $0) Version 0.2.1

Usage: gad-deploy-post HOST [WEBROOT]

HOST must be configured in ~/.ssh/config
Will clone repo to /var/repos/HOST
Deploys from /var/repos/HOST to HOST:WEBROOT
Default WEBROOT is /var/www/html
Requires a .gitignore file in repo dir to use as file mask.
.git* is not transferred to WEBROOT.
Deletes all files in WEBROOT unless they exist:
    a) in the repo
    b) in the .gitignore
"
# Print USAGE if no args
if [ $# -eq 0 ]; then
    echo "$USAGE"
    exit 1
fi

HOSTNAME="$1"
WEBROOT=${2:-/var/www/html}
REPODIR="/var/repos"
GITIGNORE="${REPODIR}/${HOSTNAME}/.gitignore"
[ -f "$GITIGNORE" ] || { echo "gitignore not found"; exit 1; }
rsync -r \
	--exclude-from="$GITIGNORE" \
	--delete \
 	${REPODIR}/${HOSTNAME}/ ${HOSTNAME}:${WEBROOT}
RSYNCERR="$?"
if [ ! "$RSYNCERR" -eq 0 ]; then
	notify "rsync exited with code $RSYNCERR for ${USER}@${HOSTNAME} while attempting to deploy ${HOSTNAME}" critical
else
    echo "rsync completed without error"
fi

wordpress-permissions "$HOSTNAME" dev
PERMERR="$?"
if [ ! "$PERMERR" -eq 0 ]; then
	echo "wordpress-permissions exited with code $PERMERR for ${USER}@${HOSTNAME}"
fi

if [ "$RSYNCERR" -eq 0 ]; then
    notify "Deploy complete for ${HOSTNAME}:${WEBROOT} by ${USER}@${HOSTNAME}"
fi

exit 0
