#!/bin/bash

# Run the latest version of certbot in docker
# Supports wildcard certs
# Usage: le-docker CREDENTIALS DOMAIN
# Requires https://hub.docker.com/r/certbot/dns-digitalocean/
# Install docker with apt-get install docker.io
# Docs:
# https://certbot-dns-digitalocean.readthedocs.io/en/latest/
# https://certbot.eff.org/docs/install.html#running-with-docker
# (The -v switch links local:remote)

USAGE="
Usage: le-wildcard DOMAIN

Appends *. to DOMAIN for wildcard
"
# Print USAGE if no args
if [ $# -lt 1 ]; then
    echo "$USAGE"
    exit 1
fi

function main {
    local CREDENTIALS DOMAIN WILDDOMAIN
    DOMAIN="$1"
    WILDDOMAIN="*.${1}"
    CREDENTIALS="/etc/letsencrypt/${DOMAIN}.ini"
    sudo docker run -it --rm --name certbot \
        -v "/etc/letsencrypt:/etc/letsencrypt" \
        -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
        certbot/dns-digitalocean \
        --server https://acme-v02.api.letsencrypt.org/directory \
        certonly \
        --dns-digitalocean-credentials "$CREDENTIALS" \
        -d "$WILDDOMAIN"
    sudo chgrp mri -R /etc/letsencrypt/archive
}

main "$@"

exit 0
