#!/bin/sh
if [ -f /usr/local/bin/tweet.sh ]; then
	rm twitter-temp.png
	pageres --crop --delay=2 --filename="twitter-temp" $1 1600x4000
	. ~/.tweet.sh.conf
	mid=$(tweet.sh upload twitter-temp.png | jq -r '.media_id_string')
	echo $mid
	rm twitter-temp.png
	tweet.sh post -m $mid "${2}"
fi
echo $1
exit 0
