#!/bin/bash
USAGE="
$(basename $0) Version 0.2.5

Usage: $(basename $0) MESSAGE ['critical' || URL] 

Sends MESSAGE as a slackbot.
URL should include the protocol, like https://site.com
If the second argument is:
- a URL, screenshots will be taken and posted along with the MESSAGE
- 'critical', MESSAGE will be tagged critical

Configured in ~/.wp-admin-config/slack.conf

Depends on:
- https://github.com/hrs/MARKOV-sentence-generator
- https://github.com/sindresorhus/pageres-cli
- https://github.com/rockymadden/slack-cli
"
# Print USAGE if no args
if [ $# -eq 0 ]; then
	echo "$USAGE"
	exit 1
fi
MESSAGE="$1"
LASTRUNFILE="${HOME}/.wp-admin-config/slack.lastrun"
[ -f "$LASTRUNFILE" ] || echo $(date +%s) > "$LASTRUNFILE"
LASTRUN=$(cat "$LASTRUNFILE")
SINCELASTRUN=$(expr $(date +%s) - $LASTRUN)

SLACK=$(which slack)
if [ ! $? -eq 0 ]; then
	echo "$(date) Could not find slack cli (https://github.com/rockymadden/slack-cli)"
	echo "$(date) ${MESSAGE}"
	exit 1
fi
if [ $SINCELASTRUN -lt 11 ]; then
	echo "$(date) ${SINCELASTRUN}s since last post. Please wait until 10s have passed. Aborting."
	echo "$(date) ${MESSAGE}"
	exit 1
else
	echo $(date +%s) > "$LASTRUNFILE"
fi

screenshot() {
	local TEMPDIR TEMPURL TEMPPIC URL PARGS MID
	local i n p
	TEMPDIR="/tmp/wordpress-notify-script/"
	[ -d "$TEMPDIR" ] || mkdir "$TEMPDIR"
	cd "$TEMPDIR"
	TEMPURL="slack-urls.tmp"
	TEMPPIC="slack-tmp"
# Cleanup temp files on exit
	trap "rm -rf ${TEMPDIR}" EXIT	
	URL="$2"
	PARGS="--crop --delay=2 --format=jpg --timeout=20"
	curl -s "${URL}" \
		| grep -Po '(?<=href=")[^"]*' \
		| grep "$URL/[a-z]" \
		| grep -v '.css\|rss\|xml\|json\|feed\|.ico\|.jpg\|.png\|.js\|.svg\|?' \
		| sort -R \
		| uniq \
		| head -n 2 \
		> ${TEMPURL};
	echo "$(date) Taking screenshots of these URLs:"
	cat "$TEMPURL"
	pageres $PARGS --filename="${TEMPPIC}-0" "$URL" 1600x2100 > /dev/null 2>&1
	pageres \
		$PARGS \
		--userAgent 'Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36' \
		--filename="${TEMPPIC}-1" \
		"$URL" \
		500x1600 \
		> /dev/null 2>&1
	n=2
	while IFS='' read -r line || [[ -n "$line" ]]; do
		pageres $PARGS --filename="${TEMPPIC}-${n}" "$line" 1600x2100 > /dev/null 2>&1
		((n++))
	done < "${TEMPURL}"
	i=0
	slack chat send "${MESSAGE}" admin --color good > /dev/null
	while [ $i -lt 5 ]; do
		p="${TEMPPIC}-${i}.jpg"
		if [ -f "$p" ]; then
			slack file upload "$p" admin
		fi
		((i++))
	done
}

echo "$(date) Tweet notification system."
if [ $# -eq 1 ]; then
	slack chat send "${MESSAGE}" admin --color good > /dev/null 2>&1
elif [ "$2" = "critical" ]; then
	slack chat send "@channel ${MESSAGE}" admin --color bad > /dev/null 2>&1
else
	screenshot "$@"
fi

echo "$(date) ${MESSAGE}"

exit 0
