#!/bin/sh
USAGE="
$(basename $0) Version 0.1.3

Usage: $(basename $0) MESSAGE 

Sends MESSAGE as a tweet from the non-critical account.
Configured in ~/.tw.conf

Depends on:
- https://github.com/hrs/MARKOV-sentence-generator
- https://github.com/piroor/tweet.sh
"
# Print USAGE if no args
if [ $# -eq 0 ]; then
    echo "$USAGE"
    exit 1
fi
MESSAGE="$1"
LASTRUNFILE="${HOME}/.tw.lastrun"
[ -f "$LASTRUNFILE" ] || echo $(date +%s) > "$LASTRUNFILE"
LASTRUN=$(cat "$LASTRUNFILE")
SINCELASTRUN=$(expr $(date +%s) - $LASTRUN)
if [ $SINCELASTRUN -lt 30 ]; then
	echo "${SINCELASTRUN}s since last tweet. Please wait until 30s have passed."
	exit 1
fi
TEXTVOL="/opt/markov-sentence-generator/360.txt.utf-8"
MARKOV=$(/opt/markov-sentence-generator/sentence-generator.py "$TEXTVOL" 5 | cut -d " " -f 1-20)
if [ -f /usr/local/bin/tweet.sh ]; then
	. "${HOME}/.tw.conf"
	tweet.sh post "${MESSAGE} ${MARKOV}" > /dev/null 2>&1
	echo $(date +%s) > "$LASTRUNFILE"
else 
	echo "Could not find tweet.sh"
fi
echo "$MESSAGE"
exit 0
