#!/bin/bash

ssh -t ${1} "\
	sudo add-apt-repository -y ppa:certbot/certbot; \
	sudo apt-get update; \
	sudo apt-get -y install certbot; \
	(sudo crontab -l ; echo '1 1 * * * /usr/bin/certbot renew --quiet --renew-hook \"/bin/systemctl reload nginx\"') | sort - | uniq - | sudo crontab -; \
	"

exit 0
