#!/bin/bash

USAGE="
$(basename $0) Version  0.2.8

Usage: $(basename $0) HOST

Deletes all posts from WordPress site on HOST.
Makes a db backup in /tmp first.
"
# Print USAGE if no args
if [ $# -eq 0 ]; then
	echo "$USAGE"
	exit 1
fi

WP=$(which wp)
[ $? != 0 ] && {echo "wp-cli not found"; exit 1}
WPCMD="$WP --ssh=${1} --path='/var/www/html'"
wordpress-backup ${1} tmp
[ $? != 0 ] && {echo "Problem making backup"; exit 1}
SITEURL=$($WPCMD option get siteurl)
[ $? != 0 ] && {echo "Problem retrieving siteurl"; exit 1}
echo "Delete ALL posts from ${SITEURL}!?"  
read -p "Are you mad? " -n 1 -r  
echo	# (optional) move to a new line  
if [[ $REPLY =~ ^[Yy]$ ]]; then  
	$WPCMD "post delete $($WPCMD "post list --format=ids")"
else
	echo "Cancelled due to sanity."
	exit 2
fi	
exit 0	
