#!/bin/bash

error_exit() {
	local lc="$BASH_COMMAND" rc=$?
	echo "Command [$lc] exited with code [$rc]"
}
trap error_exit EXIT
set -e

interactive() 
{
	scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	read -p "Database host: [localhost] " dbhost
	dbhost=${dbhost:-localhost}
	read -p "Database user: [wp] " dbuser
	dbuser=${dbuser:-wp}
	read -p "Database name: [live] " dbname
	dbname=${dbname:-live}
	read -p "Database password: " dbpass
	read -p "Domain (no http://, no www): " fqdn
	read -p "Site title: [Title] " title
	title=${title:-Title}
	read -p "WP Admin User: [admin] " user
	user=${user:-admin}
	read -p "WP Admin Password: " password
	read -p "WP Email: " email

	ssh -t ${1} "\
		cd /var/www/html; \
		wp core download; \
		wp core config \
			--dbhost=${dbhost} \
			--dbname=${dbname} \
			--dbuser=${dbuser} \
			--dbpass=${dbpass}; \
		wp core install \
			--url=${fqdn} \
			--title=${title} \
			--admin_user=${user} \
			--admin_password=${password} \
			--admin_email=${email} \
			--skip-email \
		" 
}

inline() 
{
	scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	title=$1	
	fqdn=$2
	user=$3
    email=$4
    password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 18 | head -n 1)
	dbhost="localhost"
	dbuser="wordpress"
	dbname="wordpress"
	dbpass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 18 | head -n 1)

	ssh -t ${1} "\
		cd /var/www/html; \
		wp --allow-root core download; \
		wp --allow-root core config \
			--dbhost=${dbhost} \
			--dbname=${dbname} \
			--dbuser=${dbuser} \
			--dbpass=${dbpass}; \
		wp --allow-root core install \
			--url=${fqdn} \
			--title=${title} \
			--admin_user=${user} \
			--admin_password=${password} \
			--admin_email=${email} \
			--skip-email \
		" 
        echo "WP password:"
        echo $password
}
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 HOST [DOMAIN WPUSER WPEMAIL]
    Interactive if only HOST is supplied." >&2
    exit 1
elif [ "$#" -eq 1 ]; then
    interactive $1
elif [ "$#" -gt 1 ]; then
    inline $@
fi
exit 0		
