#!/bin/bash
while IFS='' read -r line || [[ -n "$line" ]]; do
    if [[ $line == *"Host "* ]]; then
        host="${line#Host *}"
        args="--path=/var/www/html"
        ssh -q ${host} "\
		[ -f /usr/local/bin/wp ] \
		&& wp --quiet $args core is-installed \
		|| exit 1" < /dev/null
	if [ $? -eq 0 ]; then
		echo ${host}
	fi
    fi
done < ~/.ssh/config


exit 0
