#!/bin/bash
n=0
while IFS='' read -r line || [[ -n "$line" ]]; do
    if [[ $line == *"Host "* ]]; then
        host[$n]="${line#Host *}"
        args="--path=/var/www/html --ssh=${host}"
        url="$(wp $args option get siteurl)"
	wait
        echo $n ${host[$n]} $url
        ((n++))
	sleep 3
    fi
done < ~/.ssh/config


exit 0
