#!/bin/bash

USAGE="
$(basename $0) Version  0.2.8

$(basename $0) HOSTNAME WEBROOT
Resets s git repo in a remote webroot
This script tested only with root login to lsws web servers.
"

failure(){
    NOTE="$1"
    notify "$(basename $0) failed for $HOSTNAME (${NOTE})" critical
    exit 1
}

# Print USAGE if not enough args
if [ $# -lt 2 ]; then
	echo "$USAGE"
	exit 1
fi
HOSTNAME="$1"
WEBROOT="$2"
REMOTE_USER=$(ssh $HOSTNAME 'echo $USER')
if [ -z "$WEBROOT" ]; then
    failure "missing value for webroot"
fi

if [[  $REMOTE_USER == "dev" ]]; then
    echo "Fix permissions on $HOSTNAME for $REMOTE_USER"
    wordpress-permissions "$HOSTNAME" "$REMOTE_USER"
fi

echo "git reset --hard on $HOSTNAME"
ssh $HOSTNAME "cd $WEBROOT ; git add . ; git reset --hard"
[ $? -eq 0 ] || failure "git reset"

notify "git repo was reset --hard on ${HOSTNAME}."

echo "BEFORE"
ssh "$HOSTNAME" "ls -l $WEBROOT"

echo "Fix permissions manually on $HOSTNAME or CTRL-C to leave as-is"
wordpress-permissions "$HOSTNAME"

echo "AFTER"
ssh "$HOSTNAME" "ls -l $WEBROOT"

exit 0
