#!/bin/bash
wordpress-backup ${1} tmp
live=$(wp --ssh=${1} --path='/var/www/html' option get siteurl)
# Setup ssh hosts first in ~/.ssh/config
echo "Clone live db for ${1} to staging, search and replace urls, and flush cache."  
read -p "Are you sure? " -n 1 -r  
echo    # (optional) move to a new line  
if [[ $REPLY =~ ^[Yy]$ ]]  
then  
	ssh -t ${1} "\
		wp --path='/var/www/html' db export /var/www/swap.sql ;\
		wp --path='/var/www/staging' db import /var/www/swap.sql ; \
		wp --path='/var/www/staging' search-replace "${live#https://*}" "${live#https://*}:2001" --skip-columns=guid ;\
		wp --path='/var/www/staging' cache flush "
	url=$(wp --ssh=${1} --path='/var/www/staging' option get siteurl)
        echo "$url is now up to date with the live site."
fi  
exit 0  
