#!/bin/bash

USAGE="
$(basename $0) Version 0.2.1

wordpress-restore-db HOST FREQUENCY

For HOSTs on DigitalOcean only.
Restores the latest backup from FREQUENCY dir to HOST
over ssh using wp-cli.

FREQUENCY may be one of
- full
- db
- manual
- tmp
"

if [ $# -eq 0 ]; then
    echo "${USAGE}"
    exit 1
fi

# Check if there is a first argument
if [  ${1+x} ]; then
	if [ $1 == "daily" ] \
        || [ $1 == "hourly" ] \
        || [ $1 == "manual" ] \
        || [ $1 == "tmp" ]; then
		echo "Error in first argument."
		exit 1
	fi
else
	echo "Missing first argument."
	exit 1
fi

# Check if there is a second argument
if [ ${2+x} ]; then
	if [ ! $2 == "daily" ] \
        && [ ! $2 == "hourly" ] \
        && [ ! $2 == "manual" ] \
        && [ ! $2 == "tmp" ]; then
		echo "Error in second argument."
		exit 1
	fi
else
	echo "Missing second argument."
	exit 1
fi

# Check if WordPress is actually running
# See wordpress-list for explanation of this code:
args="--path=/var/www/html"
ssh -q ${1} "\
	[ -f /usr/local/bin/wp ] \
	&& wp --quiet $args core is-installed \
	|| exit 1" < /dev/null
if [ ! $? -eq 0 ]; then
	echo "${1} is not online. Proceed manually."
	exit 1
fi

host=${1}
freq=${2}
cd /tmp
cp /var/backups/wordpress/${freq}/${host}.sql.gz /tmp/restore.sql.gz
gunzip restore.sql.gz
echo "WARNING: Overwrite live db for ${host} with latest ${freq} backup?"  
read -p "Are you sure? " -n 1 -r  
echo    # (optional) move to a new line  
args="--path=/var/www/html --ssh=${1}"
scp restore.sql ${1}:/var/www/restore.sql
wp ${args} db reset
wp ${args} db import /var/www/restore.sql
rm restore.sql

exit 0
