#!/bin/bash
main ()
{
	scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	read -p "Database host: [localhost] " dbhost
	dbhost=${dbhost:-localhost}
	read -p "Database user: [wp] " dbuser
	dbuser=${dbuser:-wp}
	read -p "Database name: [live] " dbname
	dbname=${dbname:-live}
	read -p "Database password: " dbpass
	read -p "FQDN: " fqdn
	read -p "Site title: [Title] " title
	title=${title:-Title}
	read -p "User: [admin] " user
	user=${user:-admin}
	read -p "Password: " password
	read -p "Email: " email
	cd ${scriptdir}
	cp -vr assets/nginx-* /tmp
	sed -i -e "s/BRANCH/live/g" /tmp/nginx-wordpress
	sed -i -e "s/FQDN/${fqdn}/g" /tmp/nginx-wordpress
	sed -i -e "s/FQDN/${fqdn}/g" /tmp/nginx-snippets/ssl-certs.conf
	scp -r /tmp/nginx-* ${1}:
	ssh -t ${1} "\
		sudo mv nginx-letsencrypt /etc/nginx/sites-available/; \
		sudo mv nginx-wordpress /etc/nginx/sites-available/; \
		sudo mv nginx-snippets/* /etc/nginx/snippets/; \
		sudo rm /etc/nginx/sites-enabled/digitalocean; \
		sudo ln -s /etc/nginx/sites-available/nginx-letsencrypt /etc/nginx/sites-enabled/; \
		#sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048; \
		sudo service nginx restart; \
		sudo letsencrypt certonly -a webroot --webroot-path=/var/www/html -d ${fqdn}; \
		sudo rm /etc/nginx/sites-enabled/nginx-letsencrypt; \
		sudo ln -s /etc/nginx/sites-available/nginx-wordpress /etc/nginx/sites-enabled/; \
	"
	ssh ${1} "sudo cat /root/.digitalocean_password" > /tmp/stupid
	source /tmp/stupid
	ssh -t ${1} "\
		mysql -uroot -p\"${root_mysql_pass}\" -e \"drop database ${dbname}; create database ${dbname}; create user ${dbuser}@${dbhost} identified by ${dbpass}; grant all privileges on ${dbname}.* to ${dbuser}@${dbhost}; flush privileges;\" \
	"
	ssh -t ${1} "\
		cd /var/www/html; \
		wp core download; \
		wp core config \
			--dbhost=${dbhost} \
			--dbname=${dbname} \
			--dbuser=${dbuser} \
			--dbpass=${dbpass}; \
		wp db create; \
		wp core install \
			--url=${fqdn} \
			--title=${title} \
			--admin_user=${user} \
			--admin_password=${password} \
			--admin_email=${email} \
			--skip-email \
		"
	}
main ${1}
exit 0		
