#!/bin/bash

USAGE="
Usage: $(basename $0) HOST [USER]

Change primary owner of webroot to USER
while preserving write permissions for
web server to appropriate directories.
Sets all files to 644 and all directories
to 755.
"
# Print USAGE if no args
if [ $# -eq 0 ]; then
    echo "$USAGE"
    exit 1
fi
# If USER not supplied, ask for it
if [ ! ${2+x} ]; then
	read -p "User: [dev]" webroot_owner
	webroot_owner=${webroot_owner:-dev}
else
	webroot_owner=${2}
fi
while true; do
    ssh ${1} "sudo chown -R ${webroot_owner}:${webroot_owner}  /var/www/html;"
    ssh ${1} "[ -d /var/www/html/wp-content/uploads ] && \
        sudo chown -R www-data /var/www/html/wp-content/uploads; \
        [ -d /var/www/html/wp-content/banners ] && \
        sudo chown -R www-data /var/www/html/wp-content/banners; \
        [ -d /var/www/html/wp-content/plugins/wpspx-master/cache ] && \
        sudo chown -R www-data /var/www/html/wp-content/plugins/wpspx-master/cache;
    "
    ssh ${1} "sudo find /var/www/html -type f -exec chmod 644 {} +; \
        sudo find /var/www/html -type d -exec chmod 755 {} +;
    "
    [ $? -eq 0 ] && break || sleep 1
done
exit 0
