#!/bin/bash

args="--path=/var/www/html"
target=${1}.sql
backupDir="/var/backups/wordpress"
backupsToKeep=28

# Check if there is a first argument
if [  ${1+x} ]; then
	if [ $1 == "daily" ] || [ $1 == "hourly" ] || [ $1 == "manual" ] || [ $1 == "tmp" ]; then
		notify "Error in first argument, $1 $2 backup."
		exit 1
	fi
else
	notify "Missing first argument $1 $2 backup."
	exit 1
fi

# Look for the wp-cli binary, if found then run test to see if wp installed
ssh -q ${1} "\
	[ -f /usr/local/bin/wp ] \
	&& wp --quiet $args core is-installed \
	|| exit 1" < /dev/null
if [ ! $? -eq 0 ]; then
	notify "${1} is not online. What the heck?"
	exit 1
fi

function rotate()
{
	i=$backupsToKeep
	while [ $i -gt 0 ]
	do
		if [ $i -gt 1 ]; then
			h=$[i-1]
			mv ${1}.${h}.sql.gz ${1}.${i}.sql.gz >/dev/null 2>&1
		else
			mv ${1}.sql.gz ${1}.1.sql.gz >/dev/null 2>&1
		fi
		(( i-- ))
	done
}
# Next line checks if there is a second argument
if [ ${2+x} ]; then
	if [ $2 == "daily" ]; then
		cd ${backupDir}/daily
		rotate $1
	elif [ $2 == "hourly" ]; then
		cd ${backupDir}/hourly
		rotate $1
	elif [ $2 == "tmp" ]; then
		cd /tmp
		rotate $1
	fi
else
	# Set second positional argument
	set -- ${1} "manual"
	cd ${backupDir}/manual
	rotate $1
fi

ssh ${1} "wp ${args} db export /var/www/${target}"
if [ ! $? -eq 0  ]; then
	notify "Backup export failed for ${1} (${2})" 
	exit 1
fi
ssh ${1} "gzip -vf /var/www/${target}"
if [ ! $? -eq 0  ]; then
	notify "Backup gzip failed for ${1} (${2})" 
	exit 1
fi
scp ${1}:/var/www/${target}.gz .

if [ -f /usr/local/bin/restic ]; then
	rdir=~/mnt/${1}
	mkdir ${rdir}
	sshfs ${1}:/var/www ${rdir}
	restic backup ${rdir}/html --tag ${1}
	sudo umount ${rdir}
	restic backup ${target}.gz --tag ${1}
else
	notify "Restic binary not found on ${HOST}"
fi

echo $(date) "Backup completed for ${1} (${2})" 
exit 0
