#!/bin/bash

args="--path=/var/www/html"
target=${1}.sql
backupDir="/var/backups/wordpress"
backupsToKeep=28

# Check if there is no first argument
if [  ! ${1+x} ]; then
	exit 1
fi
if [ -s ~/wp.sitelist ]; then
	while read -r line; do
		echo $line
		wordpress-backup ${line} ${1} &
	done < ~/wp.sitelist
fi
exit 0
