#!/bin/bash

set -e
# Check if there is no first argument
if [  ! ${1+x} ]; then
	exit 1
fi
if [ -s ~/wp.sitelist ]; then
	while read -r line; do
		echo $line
		${1} ${line} ${2} &
	done < ~/wp.sitelist
else
	echo "~/wp.sitelist not found! You absolute maniac."
	exit 1
fi
exit 0
