#!/bin/bash
authfile=~/AUTHORIZED_KEYS
set -e
# Check if there is no first argument
if [ ! ${1+x} ]; then
	echo "Missing host argument"
	exit 1
fi
if [ -f $authfile ]; then
	ssh-keygen -lf ${authfile}
else
	echo "Master authority file not found."
	exit 1
fi

# Confirm user's intent
#echo "Replace authorized_keys file on ${1}"
#read -p "Are you sure? (y/n) " -r  
#if [[ $REPLY =~ ^[Yy]$ ]]; then  
	scp ${authfile} ${1}:.ssh/authorized_keys
#fi

exit 0
