#!/bin/bash

cmd="cd /var/www/html; \ 
	git add -A; \
	git add -A; \
	git commit -am 'Automatic update.'; \
	git config --global push.default simple; \
	git push; \
	sudo chown git-auto-deploy -R /var/www/html; \
	sudo chown www-data -R /var/www/html/wp-content/uploads; \
"
ssh -t ${1} ${cmd}
exit 0
