#!/bin/bash

function ssh_config_check {
    local HOSTPATTERN
    . "$CONFIGPARSE"
    HOSTPATTERN="^Host ${FQDN}$"
    if grep "$HOSTPATTERN" "${SSHHOSTS}"; then
        grep "$HOSTPATTERN" -A5 "${SSHHOSTS}"
        echo "${FQDN} was found in ${SSHHOSTS}"
        connection_test "$@"
        return 1
    else
        return 0
    fi
}

function ssh_config_add_host {
    . "$CONFIGPARSE"
    echo "Host ${FQDN}
    HostName ${DROPLETADDR}
    User root
    IdentityFile ${PRIVATEKEY}
    IdentitiesOnly yes
    StrictHostKeyChecking no
    " >> "${SSHHOSTS}"
}

