#!/bin/bash

# Run wordpress-install new / clone repo
# Preserve the fresh config file
function install_wordpress {
    local dbhost dbuser dbname
    . "$CONFIGPARSE"
	dbhost="localhost"
	dbuser="wordpress"
	dbname="wordpress"

	ssh -t ${FQDN} "\
		cd /var/www/html; \
		wp --allow-root core download; \
		wp --allow-root core config \
			--dbhost=${dbhost} \
			--dbname=${dbname} \
			--dbuser=${dbuser} \
			--dbpass=${DBWPPASS}; \
		wp --allow-root core install \
			--url=${FQDN} \
			--title=${HOSTNAME} \
			--admin_user=${WPUSER} \
			--admin_password=${WPPASS} \
			--admin_email=${EMAIL} \
			--skip-email \
		" 

    if [ ! $? -eq 0 ]; then
        echo "Error running wordpress-install."
        exit 1
    fi
    ssh "${FQDN}" "cp /var/www/html/wp-config.php /var/www/wp-config.php.fresh"
    if [ ! $? -eq 0 ]; then
        echo "Error copying config file."
        exit 1
    fi
    wordpress-permissions "$FQDN" dev
    if [ ! $? -eq 0 ]; then
        echo "Error setting permissions."
        exit 1
    fi
}
